#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname "$0")/.."

if [ -f "./scripts/${1}" ]; then
    ./scripts/"$1"
else
    exec "$@"
fi

# Fix file ownership for container builds
if [ -n "${DAPPER_UID}" ] && [ -n "${DAPPER_GID}" ]; then
    chown -R "${DAPPER_UID}:${DAPPER_GID}" /source/dist 2>/dev/null || :
fi
